(() => {
  const canvas = document.querySelector('#game'), ctx = canvas.getContext('2d');
  const $ = s => document.querySelector(s); const W = 1100, H = 650, ground = 535;
  let scale=1, dpr=1, last=0, raf, running=false, paused=false, level=1, score=0, coins=0, lives=3, distance=0, player, objects=[], particles=[], clouds=[], audio;
  const bestKey='coinRushBest', progressKey='coinRushLevel';
  const levels = [{speed:260,length:4500,gap:640},{speed:275,length:5000,gap:575},{speed:290,length:5500,gap:530},{speed:305,length:6000,gap:490},{speed:320,length:6500,gap:450},{speed:335,length:7000,gap:425},{speed:350,length:7600,gap:400},{speed:370,length:8200,gap:375},{speed:390,length:8800,gap:355},{speed:415,length:9500,gap:335}];
  const best = () => +(localStorage.getItem(bestKey)||0); const fmt = n => String(Math.floor(n)).padStart(6,'0');
  function resize(){ const r=canvas.getBoundingClientRect(); dpr=Math.min(devicePixelRatio||1,2); canvas.width=r.width*dpr;canvas.height=r.height*dpr; scale=r.width/W; ctx.setTransform(dpr*scale,0,0,dpr*scale,0,0); }
  addEventListener('resize',resize); resize();
  function tone(freq,dur=.1,type='sine'){ if(!audio)return; const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.05,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+dur);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+dur); }
  function music(){ if(!audio)return; tone(220,.12,'triangle'); setTimeout(()=>tone(277,.12,'triangle'),150); setTimeout(()=>tone(330,.18,'triangle'),300); }
  function init(){ const l=levels[level-1]; distance=0;coins=0;lives=3;score=(level-1)*500;player={x:145,y:ground-58,w:44,h:58,vy:0,jumps:0,frame:0,inv:0}; objects=[];particles=[]; for(let x=550;x<l.length;x+=l.gap+Math.random()*180-70){ if(Math.random()<.7) objects.push({type:'coin',x,y:ground-100-Math.random()*150,r:14,spin:Math.random()*6}); if(Math.random()<.34) objects.push({type:'rock',x:x+120,y:ground-34,w:35+Math.random()*22,h:34}); } for(let i=0;i<10;i++)clouds.push({x:Math.random()*W,y:65+Math.random()*130,s:.5+Math.random()*.8}); updateHud(); }
  function start(){ audio=audio||new (AudioContext||webkitAudioContext)(); audio.resume(); level=1;score=0;running=true;paused=false;hideAll();init(); music(); last=performance.now();raf=requestAnimationFrame(loop); }
  function jump(){ if(!running||paused)return; if(player.jumps<2){player.vy=-650;player.jumps++;tone(player.jumps===2?520:400,.11,'square'); for(let i=0;i<6;i++)burst(player.x+20,ground, '#fff');} }
  function loop(t){ if(!running)return; const dt=Math.min((t-last)/1000,.034);last=t;if(!paused)update(dt);draw();raf=requestAnimationFrame(loop); }
  function update(dt){ const l=levels[level-1];distance+=l.speed*dt; score+=l.speed*dt*.06; player.frame+=dt*10; player.vy+=1550*dt;player.y+=player.vy*dt;if(player.y>=ground-player.h){player.y=ground-player.h;player.vy=0;player.jumps=0;} if(player.inv>0)player.inv-=dt; objects.forEach(o=>{o.x-=l.speed*dt;if(o.type==='coin')o.spin+=dt*8;}); clouds.forEach(c=>{c.x-=l.speed*dt*.08;if(c.x<-150)c.x=W+100;}); objects=objects.filter(o=>o.x>-100); if(distance>l.length){complete();return;} for(const o of objects){if(o.hit)continue;const box={x:player.x+7,y:player.y+5,w:player.w-14,h:player.h-8};if(o.type==='coin'&&Math.hypot((box.x+box.w/2)-(o.x), (box.y+box.h/2)-o.y)<32){o.hit=true;coins++;score+=100;burst(o.x,o.y,'#ffd84d');tone(880,.09,'sine');} if(o.type==='rock'&&box.x<o.x+o.w&&box.x+box.w>o.x&&box.y<o.y+o.h&&box.y+box.h>o.y){o.hit=true;hurt();}} objects=objects.filter(o=>!o.hit||o.type==='rock'&&o.hit&&o.x>0);particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=500*dt;p.life-=dt;});particles=particles.filter(p=>p.life>0);updateHud(); }
  function hurt(){ if(player.inv>0)return;lives--;player.inv=1.5;score=Math.max(0,score-150);tone(110,.25,'sawtooth'); for(let i=0;i<15;i++)burst(player.x+20,player.y+25,'#ff5b72');if(lives<=0)gameOver(); }
  function complete(){running=false;score+=lives*250+coins*50;localStorage.setItem(bestKey,Math.max(best(),Math.floor(score)));$('#levelTitle').textContent='LEVEL '+level;$('#resultScore').textContent=fmt(score);$('#resultCoins').textContent=coins;$('#nextBtn').textContent=level===10?'FINISH RUN →':'NEXT LEVEL →';$('#levelPanel').classList.add('active');tone(660,.12);setTimeout(()=>tone(880,.2),140); }
  function gameOver(){running=false;localStorage.setItem(bestKey,Math.max(best(),Math.floor(score)));$('#overScore').textContent=fmt(score);$('#gameOverPanel').classList.add('active');}
  function burst(x,y,color){particles.push({x,y,vx:(Math.random()-.5)*150,vy:-Math.random()*180,life:.6+Math.random()*.5,color});}
  function updateHud(){$('#score').textContent=fmt(score);$('#level').textContent=level;$('#lives').textContent=lives;$('#bestScore').textContent=fmt(best());}
  function hideAll(){document.querySelectorAll('.overlay').forEach(x=>x.classList.remove('active'));}
  function togglePause(){if(!running)return;paused=!paused;$('#pausePanel').classList.toggle('active',paused);$('#pauseBtn').textContent=paused?'▶':'Ⅱ';if(!paused)last=performance.now();}
  function roundRect(x,y,w,h,r,fill){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=fill;ctx.fill();}
  function draw(){ctx.clearRect(0,0,W,H);const l=levels[level-1];const hue=(level-1)*5;let sky=ctx.createLinearGradient(0,0,0,H);sky.addColorStop(0,`hsl(${190+hue},75%,73%)`);sky.addColorStop(1,`hsl(${205+hue},75%,88%)`);ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);ctx.fillStyle='#ffffff55';clouds.forEach(c=>{ctx.beginPath();ctx.arc(c.x,c.y,35*c.s,0,7);ctx.arc(c.x+35*c.s,c.y+8*c.s,25*c.s,0,7);ctx.arc(c.x-32*c.s,c.y+10*c.s,22*c.s,0,7);ctx.fill();});ctx.fillStyle=`hsl(${115+hue},45%,55%)`;ctx.beginPath();ctx.moveTo(0,ground);for(let x=0;x<=W;x+=80)ctx.lineTo(x,ground-35-Math.sin(x*.01+level)*25);ctx.lineTo(W,H);ctx.lineTo(0,H);ctx.fill();ctx.fillStyle='#45b957';ctx.fillRect(0,ground,W,H-ground);ctx.fillStyle='#278f4a';ctx.fillRect(0,ground,W,8);ctx.strokeStyle='#65dc65';ctx.lineWidth=4;for(let x=0;x<W;x+=45){ctx.beginPath();ctx.moveTo(x,ground+8);ctx.lineTo(x+8,ground+18);ctx.stroke();} objects.forEach(o=>{if(o.type==='coin')drawCoin(o);else drawRock(o);});drawPlayer();particles.forEach(p=>{ctx.globalAlpha=Math.max(p.life,0);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,5,5);});ctx.globalAlpha=1; }
  function drawCoin(o){ctx.save();ctx.translate(o.x,o.y);ctx.scale(Math.abs(Math.cos(o.spin))*.7+.3,1);ctx.beginPath();ctx.arc(0,0,o.r,0,7);ctx.fillStyle='#ffc928';ctx.fill();ctx.lineWidth=3;ctx.strokeStyle='#fff17d';ctx.stroke();ctx.fillStyle='#e39816';ctx.font='bold 17px Nunito';ctx.textAlign='center';ctx.fillText('$',0,6);ctx.restore();}
  function drawRock(o){ctx.fillStyle='#723f91';ctx.beginPath();ctx.moveTo(o.x,o.y+o.h);ctx.lineTo(o.x+5,o.y+12);ctx.lineTo(o.x+o.w*.45,o.y);ctx.lineTo(o.x+o.w-3,o.y+10);ctx.lineTo(o.x+o.w,o.y+o.h);ctx.fill();ctx.fillStyle='#9c65b6';ctx.fillRect(o.x+9,o.y+12,7,8);}
  function drawPlayer(){if(player.inv>0&&Math.floor(player.inv*12)%2===0)return;const x=player.x,y=player.y,run=Math.sin(player.frame)*6;ctx.save();ctx.translate(x,y);ctx.fillStyle='#f04868';ctx.beginPath();ctx.arc(22,14,16,0,7);ctx.fill();ctx.fillStyle='#ffcf9e';ctx.beginPath();ctx.arc(22,17,13,0,7);ctx.fill();ctx.fillStyle='#5a348e';ctx.beginPath();ctx.arc(10,10,15,3.5,6.1);ctx.fill();ctx.fillStyle='#07143c';ctx.beginPath();ctx.arc(27,16,2.5,0,7);ctx.fill();ctx.strokeStyle='#ffcf9e';ctx.lineWidth=7;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(12,34);ctx.lineTo(8-run,48);ctx.moveTo(30,34);ctx.lineTo(36+run,48);ctx.stroke();ctx.strokeStyle='#f04868';ctx.lineWidth=10;ctx.beginPath();ctx.moveTo(13,31);ctx.lineTo(32,31);ctx.stroke();ctx.restore();}
  addEventListener('keydown',e=>{if(['Space','ArrowUp'].includes(e.code)){e.preventDefault();jump();}if(e.code==='KeyP')togglePause();});canvas.addEventListener('pointerdown',e=>{if(running&&!paused)jump();});$('#playBtn').onclick=start;$('#pauseBtn').onclick=togglePause;$('#resumeBtn').onclick=togglePause;$('#restartBtn').onclick=()=>{hideAll();running=true;paused=false;init();last=performance.now();};$('#tryAgainBtn').onclick=()=>{hideAll();running=true;init();last=performance.now();};$('#homeBtn').onclick=()=>{hideAll();$('#menu').classList.add('active');updateHud();};$('#nextBtn').onclick=()=>{if(level<10){level++;hideAll();running=true;init();last=performance.now();music();}else{hideAll();$('#menu').classList.add('active');updateHud();}}; updateHud();
})();
